---

# TCP port used by etcd clients. Also resides in
# roles/etcd/defaults/main.yaml
etcd_client_port: 2379

#flannel_version
flannel_version: 0.5.5
flannel_destination: "{{ destination_directory }}/flannel"

#The backend that flannel should use
flannel_backend: vxlan

#The default url to download the flannel tar from
flannel_download_url_base: "https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}"
flannel_download_url: "{{ flannel_download_url_base }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"

flannel_config_dir: /etc/flannel

# vi:syntax=yaml
