---

- name: installing latest kernel version
  apt: name=linux-generic-lts-vivid state=latest update_cache=yes
  register: kernel_install

- fail: msg="You need to reboot server into new kernel to continue"
  when: not reboot_on_kernel_update

- name: rebooting server into new kernel
  shell: sleep 2 && shutdown -r now "rebooting server for update"
  when: kernel_install.changed
  register: reboot_servers
  ignore_errors: true
  async: 1
  poll: 0

- name: waiting server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=300
  when: reboot_servers.started|default(false)
  sudo: false

# vi:syntax=yaml
