---

- name: docker_restart
  command: /bin/true
  notify:
    - docker_stop
    - docker_delete_docker0
    - docker_start

- name: docker_stop
  service: name=docker state=stopped

- name: docker_delete_docker0
  command: ip link delete docker0
  when: '"docker0" in ansible_interfaces'

- name: docker_start
  service: name=docker state=started

# vi:syntax=yaml
