---

etcd_version: 3.0.1
etcd_destination: "{{ destination_directory }}/etcd"
etcd_peers_group: etcd

etcd_url_scheme: http
etcd_peer_url_scheme: http

etcd_client_port: 2379
etcd_peer_port: 2380

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8s-cluster

etcd_data_dir: /var/lib/etcd
etcd_config_dir: /etc/etcd

etcd_interface: "{{ ansible_default_ipv4.interface }}"
etcd_machine_address: "{{ hostvars[inventory_hostname]['ansible_' ~ etcd_interface].ipv4.address }}"
etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_listen_client_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"
etcd_initial_advertise_peer_urls: "{{ etcd_peer_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_peer_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_client_port }}"

etcd_download_url_base: "https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}"
etcd_download_url: "{{ etcd_download_url_base }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"

etcd_enabled: true

# vi:syntax=yaml
