---

- name: creating kubernetes directories
  file: path={{ item }} state=directory recurse=yes force=yes
  with_items:
    - "{{ kube_manifest_dir }}"
    - "{{ kube_config_dir }}"
    - "{{ kube_script_dir }}"
    - "{{ kube_cert_dir }}"
    - "{{ kube_ssl_dir }}"
    - "{{ kube_bin_dir }}"

- name: writing global config file for services
  template: src=etc/kubernetes/config.j2 dest={{ kube_config_dir }}/config

# vi:syntax=yaml
